from typing import List

from incendium.helper.types import AnyStr

def send_html_email(
    subject: AnyStr, body: AnyStr, to: List[AnyStr], priority: AnyStr = ...
) -> None: ...
def send_high_priority_email(
    subject: AnyStr, body: AnyStr, to: List[AnyStr]
) -> None: ...
def send_plain_text_email(
    subject: AnyStr, body: AnyStr, to: List[AnyStr], priority: AnyStr = ...
) -> None: ...
