ignore: []

refactor:
  include: []
  skip:
    - dict-assign-update-to-union
    - lift-return-into-if
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: '3.5'

metrics:
  quality_threshold: 25.0

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false

github:
  labels: []
  ignore_labels: [sourcery-ignore]
  request_review: author
  sourcery_branch: sourcery/{base_branch}
