[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.isort]
line_length= 79
profile = "black"
py_version = 27

[tool.pydocstyle]
convention = "google"
