[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ["py27"]

[tool.isort]
profile = "black"
line_length= 79
py_version = 27

[tool.pydocstyle]
convention = "google"
