from typing import Optional

from incendium.helper.types import AnyStr, DictStringAny

def swap_windows(
    from_path: AnyStr, to_path: AnyStr, params: Optional[DictStringAny] = ...
) -> None: ...
def swap_to(path: AnyStr, params: Optional[DictStringAny] = ...) -> None: ...
