from typing import List, Optional, Tuple

from incendium.helper.types import AnyStr

class Label:
    dpmm: int
    height: int
    width: int
    def __init__(
        self, height: int = ..., width: int = ..., dpmm: int = ...
    ) -> None: ...
    @property
    def code(self) -> AnyStr: ...
    @code.setter
    def code(self, value: AnyStr) -> None: ...
    def dump_zpl(self) -> AnyStr: ...
    def barcode_field_default(
        self, module_width: float, bar_width_ratio: float, height: int
    ) -> None: ...
    def comment(self, comment: AnyStr) -> None: ...
    def end_origin(self) -> None: ...
    def field_block(
        self, width: int, justification: AnyStr = ..., lines: int = ...
    ) -> None: ...
    def field_origin(
        self, x: int, y: int, justification: Optional[AnyStr] = ...
    ) -> None: ...
    def field_orientation(
        self, orientation: AnyStr, justification: Optional[AnyStr] = ...
    ) -> None: ...
    def change_international_font(
        self, character_set: int = ..., remaps: Optional[List[Tuple[int, int]]] = ...
    ) -> None: ...
    def graphic_box(
        self,
        width: int,
        height: int,
        thickness: int = ...,
        color: AnyStr = ...,
        rounding: int = ...,
    ) -> None: ...
    def graphic_circle(
        self, diameter: int, thickness: int = ..., color: AnyStr = ...
    ) -> None: ...
    def graphic_ellipse(
        self, width: int, height: int, thickness: int = ..., color: AnyStr = ...
    ) -> None: ...
    def home(self, x: int, y: int, justification: Optional[AnyStr] = ...) -> None: ...
    def load_definition(self, path: AnyStr) -> None: ...
    def modify_darkness(self, value: int) -> None: ...
    def print_graphic(
        self, path: AnyStr, magnification_x: int = ..., magnification_y: int = ...
    ) -> None: ...
    def reverse_print(self, active: AnyStr = ...) -> None: ...
    def save_format(self, path: AnyStr) -> None: ...
    def set_darkness(self, value: int) -> None: ...
    def set_default_font(
        self, height: int, width: Optional[int] = ..., font: AnyStr = ...
    ) -> None: ...
    def text_block(
        self, width: int, height: int, orientation: AnyStr = ...
    ) -> None: ...
    def write_barcode(
        self,
        height: int,
        barcode_type: AnyStr,
        orientation: AnyStr = ...,
        check_digit: AnyStr = ...,
        print_interpretation_line: AnyStr = ...,
        print_interpretation_line_above: AnyStr = ...,
        magnification: int = ...,
        error_correction: AnyStr = ...,
        mask: AnyStr = ...,
        mode: AnyStr = ...,
    ) -> None: ...
    def write_field_number(
        self,
        number: int,
        char_height: Optional[int] = ...,
        char_width: Optional[int] = ...,
        font: AnyStr = ...,
        orientation: AnyStr = ...,
        line_width: Optional[int] = ...,
        max_line: int = ...,
        line_spaces: int = ...,
        justification: AnyStr = ...,
        hanging_indent: int = ...,
    ) -> None: ...
    def write_text(
        self,
        text: AnyStr,
        char_height: Optional[int] = ...,
        char_width: Optional[int] = ...,
        font: AnyStr = ...,
        orientation: AnyStr = ...,
        line_width: Optional[int] = ...,
        max_line: int = ...,
        line_spaces: int = ...,
        justification: AnyStr = ...,
        hanging_indent: int = ...,
    ) -> None: ...
