name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    uses: coatl-dev/workflows/.github/workflows/pre-commit.yml@0d24a98543a7e17f432503425e6ef836972864bb # v7.0.28
    with:
      skip-hooks: 'pylint'

  pylint:
    needs: pre-commit
    uses: coatl-dev/workflows/.github/workflows/pylint.yml@0d24a98543a7e17f432503425e6ef836972864bb # v7.0.28

  jython:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      JYTHON_CACHE_DIR: $HOME/.cache/jython
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Jython
        uses: coatl-dev/actions/setup-jython@45ee24a8c8397a346538acefea6221e30076fa66 # v7.0.14
        id: setup-jython
        with:
          jython-version: '2.7.3'

      - name: Cache Jython
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.JYTHON_CACHE_DIR }}
          key: jy-${{ steps.setup-jython.outputs.jython-version }}-${{ runner.os }}-${{ steps.setup-jython.outputs.java-distribution }}-${{ steps.setup-jython.outputs.java-version }}-${{ hashFiles('setup.py') }}

      - name: Test installation on Jython
        run: |
          make install JYTHON_CACHE_DIR=${{ env.JYTHON_CACHE_DIR }}

  tox-package:
    if: ${{ github.event_name == 'pull_request' }}
    uses: coatl-dev/workflows/.github/workflows/tox-docker.yml@0d24a98543a7e17f432503425e6ef836972864bb # v7.0.28

  tox-stubs:
    if: ${{ github.event_name == 'pull_request' }}
    uses: coatl-dev/workflows/.github/workflows/tox.yml@0d24a98543a7e17f432503425e6ef836972864bb # v7.0.28
    with:
      python-versions: |
        3.9
        3.10
        3.11
        3.12
      working-directory: stubs
