name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    runs-on: ubuntu-latest
    container: coatldev/six:3.10.11a0
    steps:
      - name: List pyenv versions
        run: |
          pyenv versions

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox

      - name: Run tests
        run: |
          tox
