name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    runs-on: ubuntu-latest
    container: coatldev/six:3.10.11a3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List pyenv versions
        run: |
          pyenv versions

      - name: Install dependencies
        run: |
          pipx install tox

      - name: Run tests
        run: |
          tox
