name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    runs-on: ubuntu-latest
    container:
      image: coatldev/six:3.10.11b0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: whoami
        run: |
          whoami

      - name: Install dependencies
        run: |
          python -m pip install tox

      - name: Run tests
        run: |
          tox

      - name: Test build
        run: |
          python2 -m pip install build twine
          python2 -m build
