name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    uses: thecesrom/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      image: ubuntu-20.04
      pre-commit: true
