name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    runs-on: ubuntu-latest
    container: coatldev/six:3.10.11a2
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List pyenv versions
        run: |
          pyenv versions

      - name: Install dependencies
        run: |
          python -m pip install \
            --no-cache-dir \
            --upgrade \
            pip
          python -m pip install \
            --no-cache-dir \
            --user \
            tox

      - name: Run tests
        run: |
          python -m tox
