name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    runs-on: ubuntu-latest
    container:
      image: coatldev/six:3.10.11b0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install tox

      - name: set TOX
        run: echo "TOX=$(tox --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache tox
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ env.TOX }}-${{ hashFiles('tox.ini') }}

      - name: Run tests
        run: |
          tox
