name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tox:
    runs-on: ubuntu-latest
    container:
      image: coatldev/six:gh-3.10.11a2
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir tox
          pyenv rehash

      - name: Environment
        run: |
          printenv

      - name: pre pre-commit tests
        run: |
          which -a git
          type git
          file /usr/bin/git

      - name: Run tests
        run: |
          tox

      - name: pre-commit.log
        if: always()
        run: |
          cat /github/home/.cache/pre-commit/pre-commit.log
