name: publish

on:
  release:
    types:
      - published

jobs:
  tox-package:
    if: ${{ github.event_name == 'pull_request' }}
    uses: coatl-dev/workflows/.github/workflows/tox-docker.yml@8d3c0aba2a053986bce9382063facccf1fd98247 # v7.0.0

  tox-stubs:
    if: ${{ github.event_name == 'pull_request' }}
    uses: coatl-dev/workflows/.github/workflows/tox.yml@8d3c0aba2a053986bce9382063facccf1fd98247 # v7.0.0
    with:
      python-versions: |
        3.9
        3.10
        3.11
        3.12
      working-directory: stubs

  pypi-publish-package:
    needs: [tox-package]
    uses: coatl-dev/workflows/.github/workflows/pypi-upload.yml@8d3c0aba2a053986bce9382063facccf1fd98247 # v7.0.0
    with:
      python-version: '2.7'
      url: 'https://upload.pypi.org/legacy/'
      username: '__token__'
    secrets:
      password: ${{ secrets.PYPI_API_TOKEN_INCENDIUM_PKG }}

  pypi-publish-stubs:
    needs: [tox-stubs]
    uses: coatl-dev/workflows/.github/workflows/pypi-upload.yml@8d3c0aba2a053986bce9382063facccf1fd98247 # v7.0.0
    with:
      python-version: '3.12'
      url: 'https://upload.pypi.org/legacy/'
      username: '__token__'
      working-directory: 'stubs'
    secrets:
      password: ${{ secrets.PYPI_API_TOKEN_INCENDIUM_STUBS }}
