name: pylint

on: [push, pull_request]

env:
  PYTHON_VERSION: '3.10'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
