name: Pylint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
    - name: Analysing code with pylint
      run: |
        pylint src
      if: ${{ github.ref == 'refs/heads/code' }}
    - name: Analysing project with pylint
      run: |
        pylint $(git ls-files '*.py')
      if: ${{ github.ref == 'refs/heads/project' }}
